### ISSUE TITLE
GitLab-CI/CD 代码管理及自动测试及部署到远程服务器

### ISSUE THREAD

**Issue by mikuh** [mikuh/mikuh.github.io#1]
首先什么是CI、CD呢？

CI/CD 中的“CI”始终指持续集成，它属于开发人员的自动化流程。成功的 CI 意味着应用代码的新更改会定期构建、测试并合并到共享存储库中。该解决方案可以解决在一次开发中有太多应用分支，从而导致相互冲突的问题。

CI/CD 中的“CD”指的是持续交付和/或持续部署，这些相关概念有时会交叉使用。两者都事关管道后续阶段的自动化，但它们有时也会单独使用，用于说明自动化程度。

下面，我们通过一个Python项目来实践整个过程。

## 搭建Gitlab服务器及设置Gitlab-runner

这个过程比较简单，自行参考官方文档。这里就不说了，网上这方面的资料也很多。

**Gitlab**这个东西就是实现一个自托管的Git项目仓库，并且可以通过Web界面进行可视化访问项目代码，用起来跟github没什么区别。就不多废话了。

**Gitlab-runner**则是`.gitlab-ci.yml`脚本的运行器，Gitlab-runner是基于Gitlab-CI的API进行构建的相互隔离的机器（或虚拟机）

我这里为了方便，就直接使用[https://gitlab.com](https://gitlab.com/)提供的公共服务了，这里建议小团队就直接拿公共的服务用，速度还可以，也不需要自己搭和维护了，搭建的过程其实坑还是蛮多的。

当然如果要自己安装的话可以参考我写的这个例子：<https://github.com/mikuh/gitlab_server>

## 创建项目

我们到`gitlab.com`上创建一个项目，然后`clone`到本地。

这里就以docker创建Django项目为例，在项目根目录如下编写`Dockerfile`以及docker-compose.yml.

Dockerfile:

```txt
FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
COPY pip.conf /code/
RUN mkdir ~/.pip/ && cp pip.conf ~/.pip/
RUN pip install -r requirements.txt
```

其中pip.conf是为了修改pip源。

docker-compose.yml:

```yaml
version: '3'

services:
  web:
    container_name: drf_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres


  postgres:
    image: postgres:11.5
    restart: always
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: 'tutorial'
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql
```

使用Django提供的工具可以很轻松的生成一个项目：

```shell
django-admin startproject tutorial .
```

然后创建一个app：

```shell
python manage.py startapp snippets
```

------

构建这个项目的过程这里就不多说了，自己去写。

## 编写.gitlab-ci.yml文件

```yaml
image: python:3.7
stages:
  - test
  - deploy
services:
  - postgres:11.5

variables:
  POSTGRES_DB: tutorial
  POSTGRES_USER: root
  POSTGRES_PASSWORD: "1234"


test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt

    - python manage.py test
```

将这个文件push到gitlab.com就实现CI控制了。

我们每次向gitlab.com提交代码，都会自动运行测试。

![1567412371961](https://github.com/mikuh/mikuh.github.io/blob/master/images/gitlab1.png)

接下来，我们来实现CD。

## 实现远程服务器的自动部署

因为我们的服务器和gitlab-runner并不是一起的，于是自然的想法就是使用ssh来实现远端的部署。

因此，这里的重点就是如何实现在`gitlab.com`的docker环境，ssh到我们的生产服务器，并执行相关的部署语句。

因为是自动化部署，自然是没办法输入ssh密码的，于是我们需要用密钥的方式，因此，我们需要在gitlab上添加相关的变量：

![1567411751259](https://github.com/mikuh/mikuh.github.io/blob/master/images/gitlab2.png)

我们将自己本地开发环境的有权访问生产环境的 ssh private_key 作为变量放在gitlab.com上，还有相应的用户，以便在`.gitlab-ci.yml`中调用，使gitlab.com的gitlab-runner生成的docker容器具有和我们开发环境本地同样的对生产环境的操作权限。

在配置好Variables之后，我们来完善deploy部分的设置：

```yaml
···
deploy-dev:
  stage: deploy
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o "StrictHostKeyChecking=no" -p22 $USER "cd /home && if ! test -d '/home/tutorial';then git clone git@gitlab.com:mikuh/tutorial.git;fi"
    - ssh -p22 $USER "cd /home/drf_tutorial && git pull"
    - ssh -p22 $USER "cd /home/drf_tutorial && docker-compose up -d --build web"
```

把修改好的`.gitlab-ci.yml` push到gitlab.com的仓库，就大功告成了。现在每次我们push代码过去，gitlab-runner都会按照我们的设置自动执行相应的test和deploy,将每次修改部署到生产环境了。

以后我们持续开发以及迭代部署的时候就非常方便了，只需要改代码push即可，不需要做其他额外的工作，极大的提高了工作效率~
